### ISSUE TITLE
plz update gem 

### ISSUE THREAD

**Issue by alireza-mohagheghi** [hzamani/parsi-date#11]
irb(main):002:0> Parsi::Date.parse "1391/10/12"

.gem/ruby/2.5.0/gems/parsi-date-0.3.1/lib/parsi-date.rb:192: warning: constant ::Fixnum is deprecated

your gem not update

**Comment by salmanmp** [comment]
Is it legal to publish updated source as another gem?

**Comment by ahangarha** [comment]
> Is it legal to publish updated source as another gem?

Sure it is. It is released under MIT. As long as you follow the license, you can fork this project, and put your copyright to what you modify or add.

Please let me know if you are going to fork and maintain a new gem out of this.

I wish we could get in touch with @hzamani. So if he cannot maintain, another person does it.
