### ISSUE TITLE
Wrong recognize leap years 1403 and 1404

### ISSUE THREAD

**Issue by mahdine** [hzamani/parsi-date#13]
According to reliable sources ([Geophysics](https://calendar.ut.ac.ir/Fa/News/Data/Doc/KabiseShamsi1206-1498-new.pdf) , [Solar Hijri calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar), [time.ir](https://www.time.ir/fa/jalalicalendar)) the year 1403 is a leap year but this library has different calculation.

**Comment by martianboy** [comment]
Thanks for reporting this! Would you be able to send a PR for fixing it?

**Comment by martianboy** [comment]
Thanks for reporting this! Would you be able to send a PR for fixing it?
