### ISSUE TITLE
How to install parsi-date

### ISSUE THREAD

**Issue by mohsentaheris** [hzamani/parsi-date#5]
Hi,
I'm using ubuntu and ruby 1.9.1
I try to install it by following command:
#>gem install parsi-date
but it returns with following errors:
unable to convert U+0641 from UTF-8 to US-ASCII for lib/parsi-date.rb, skipping
unable to convert "\xD8" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
unable to convert U+062F from UTF-8 to US-ASCII for spec/parsi-date/strftime_spec.rb, skipping
unable to convert U+0641 from UTF-8 to US-ASCII for spec/parsi-date/constants_spec.rb, skipping
 
could you help me on how to install it?

**Comment by intuxicated** [comment]
Try this:

```bash
gem update rdoc
```
And install parsi-date gem again.

**Comment by mohsentaheris** [comment]
@intuxicated thanks for your answer, I install it by following command:
gem install parsi-date --no-rdoc --no-ri
but I don't know how to use it on ruby and rails project(redmine)
it says:
NoMethodError (undefined method `to_parsi' for Mon, 13 Apr 2015:Date)

is there any other installation needed?

**Comment by intuxicated** [comment]
Yep. Add this line to your `Gemfile` (before `# Load plugins' Gemfiles`) :
```bash
gem "parsi-date"
```
And run bundle command :
```bash
bundle install
```

**Comment by mohsentaheris** [comment]
@intuxicated I don't know how to thank you.
you save my day
:+1:

**Comment by intuxicated** [comment]
Your welcome.

btw which part of first answer solved your problem with encoding ? rdoc or locale things or both ?

**Comment by mohsentaheris** [comment]
when I tried to update `rdoc` lt uses some https links that my isp blocked them.
so I install `parsi-date` with  `--no-rdoc --no-ri` options and it works fine.

thanks again
